// var name ="dipesh";
// var age ="20";
// var isEmployed=true;
// console.log(name);
// console.log(age);
// var age="50";
// console.log(age);
// let name ="dipesh";
// let age ="20";
// let isEmployed=true;
// console.log(name);
//  console.log(age);
// let age="50";
//  console.log(age);
//  if(true)
//  {
//     var age=30;
    
//  }
//  console.log(age);
// node
//  const PI =3.14;
//  console.log(PI);
//  PI=3.14159;
//  console.log(PI);
// console.log(typeof name);
// console.log(typeof age);
// console.log(typeof isEmployed);
// let name ="Dipesh";
// let age1=20;

//console.log("My Name is "+ name + " and my age "+ age1);//OLD METHOD OF CONACATENATION
//console.log(`My name is ${name} and my age is ${age1} `);// NEW METHOD OF CONCATENATION
let data =null;
console.log(data);